apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuyk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tuyk
  template:
    metadata:
      labels:
        app: tuyk
    spec:
      containers:
      - image: okteto.dev/tuyk:latest
        name: tuyk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "51b61fee-67f4-4cff-ae64-16c8c837c693"
        - name: Vless_Path
          value: "/51b61fee-67f4-4cff-ae64-16c8c837c693"
        - name: Vmess_UUID
          value: "cb99fdce-14e8-44c7-bc67-a66c2ba939f5"
        - name: Vmess_Path
          value: "/cb99fdce-14e8-44c7-bc67-a66c2ba939f5"
        - name: Share_Path
          value: "/Share233"
