apiVersion: apps/v1
kind: Deployment
metadata:
  name: emor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emor
  template:
    metadata:
      labels:
        app: emor
    spec:
      containers:
      - image: okteto.dev/emor:latest
        name: emor
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "51b61fee-67f4-4cff-ae64-16c8c837c693"
        - name: Vless_Path
          value: "/51b61fee-67f4-4cff-ae64-16c8c837c693"
        - name: Vmess_UUID
          value: "cb99fdce-14e8-44c7-bc67-a66c2ba939f5"
        - name: Vmess_Path
          value: "/cb99fdce-14e8-44c7-bc67-a66c2ba939f5"
        - name: Share_Path
          value: "/Share039"
