apiVersion: v1
kind: Service
metadata:
  name: tuyk
  annotations:
    dev.okteto.com/auto-ingress: "tuyk"
spec:
  type: ClusterIP  
  ports:
  - name: "tuyk"
    port: 8080
  selector:
    app: tuyk
