apiVersion: v1
kind: Service
metadata:
  name: peot
  annotations:
    dev.okteto.com/auto-ingress: "peot"
spec:
  type: ClusterIP  
  ports:
  - name: "peot"
    port: 8080
  selector:
    app: peot
